#ifndef ARDUINO_CREDENTIALS_H
#define ARDUINO_CREDENTIALS_H

/* WiFi Credentials*/
#define STA_SSID "YOUR_WIFI_SSID"
#define STA_PASS "YOUR_WIFI_PASS"

/* MQTT Credentials */
#define MQTT_USERNAME "YOUR_MQTT_USERNAME"
#define MQTT_KEY      "YOUR_MQTT_PASS"
#define MQTT_TOPIC    "YOUR_MQTT_TEST_TOPIC"

#endif /* ARDUINO_CREDENTIALS_H */
